# Generated by Django 3.2.2 on 2021-05-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmn',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sd',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
