# Generated by Django 3.2.2 on 2021-05-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpency', '0002_auto_20210526_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmn',
            name='idSD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpency.sd'),
        ),
    ]
