# Generated by Django 3.2.2 on 2021-05-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpency', '0003_alter_bpmn_idsd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpency.user'),
        ),
    ]
