# Generated by Django 3.2.2 on 2021-05-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpency', '0004_alter_sd_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd',
            name='idUser',
            field=models.CharField(default='2', max_length=12),
        ),
    ]
