# Generated by Django 3.2.2 on 2021-06-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpency', '0008_auto_20210604_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
