# Generated by Django 3.2.2 on 2021-06-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpency', '0011_auto_20210611_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sd',
            old_name='timestamp',
            new_name='timestam',
        ),
    ]
