# Generated by Django 3.2.2 on 2021-06-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpency', '0012_rename_timestamp_sd_timestam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sd',
            old_name='timestam',
            new_name='timestamp',
        ),
    ]
